project_id = "fbkprtfdoeoazfgmsecm"

[functions.send-email]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.email-secrets-status]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = true
